name: geekreep
description: geekreep

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: 
  shared_preferences: 
  go_router: 
  url_launcher_android:
  url_launcher_ios:  
  firebase_core: 
  firebase_auth: 
  google_sign_in:

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
